### ISSUE TITLE
Unable to scroll inside InfoBox

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlemaps/v3-utility-library#19]
```
If the content of the InfoBox overflows, you can't use the scrollbar to scroll 
down because it will drag the map instead.

Any ideas? 
```

Original issue reported on code.google.com by `mongopr...@gmail.com` on 2 Jul 2010 at 9:38

**Comment by matthiaskomarek** [comment]
Is there any solution for this? I am hitting the same problem on iOS devices when i try to scroll inside a InfoWindow

**Comment by rolanyang** [comment]
My fix was to not let the content overflow.

wrap your infowindow content in

`<div class="infowindow">contentthat'slreallylongandoverflowsbreakingthescrollonmobiledevices</div>`

add to your styles:
```
.infowindow {
   /* overflow breaks vertical scrolling on mobile devices, so don't let it overflow! */
   overflow:hidden !important; 
}
```
