### ISSUE TITLE
Images missing in examples since migration

### ISSUE THREAD

**Issue by stephenmcd** [googlemaps/v3-utility-library#344]
See https://code.google.com/p/gmaps-api-issues/issues/detail?id=9743

**Comment by elau8465** [comment]
It's not just the examples, actually. The code itself attempts to load images from Google Code:
MarkerClusterer.prototype.MARKER_CLUSTER_IMAGE_PATH_ =
    'http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/' +
    'images/m';
on line 195 of https://github.com/googlemaps/v3-utility-library/blob/master/markerclusterer/src/markerclusterer.js

**Comment by sailor** [comment]
I've created a pull request to fix this issue: https://github.com/googlemaps/v3-utility-library/pull/345

**Comment by PeterTheOne** [comment]
You don't need to update `MARKER_CLUSTER_IMAGE_PATH_`, you can just set the `imagePath` option to the path of the local images.

**Comment by richardpenman** [comment]
@PeterTheOne - does that work for you? Seems there is no longer such an option so I used MARKER_CLUSTER_IMAGE_PATH_.

**Comment by PeterTheOne** [comment]
@richardpenman Yes and there still is:
`var mc = new MarkerClusterer(map, makers, {imagePath: 'images/m'});`

**Comment by PeterTheOne** [comment]
fixed in d2cf3a584f90829859629e210d76944287c4d741
