### ISSUE TITLE
Markers with label not showing in google chrome after deploying on IIS production

### ISSUE THREAD

**Issue by akash2go** [googlemaps/v3-utility-library#347]
My application is using markerwithlabel library.It works well while in development environment on google chrome.But after deploying the application on IIS production , the markers are not visible in google chrome while they are visible in IE and Firefox.Please suggest a solution as most of the users are having google chrome installed on their machine.

**Comment by davidpelayo** [comment]
Please provide more details.
Error details, screenshots, links if the apps are public or not, and things like that.
Otherwise is nearly impossible to know what's the issue and how to help you to solve it.
