### ISSUE TITLE
Sync with googlemaps/js-marker-clusterer repo

### ISSUE THREAD

**Issue by PeterTheOne** [googlemaps/v3-utility-library#348]
Please keep markerclusterer and markerclustererplus in this repository in sync with https://github.com/googlemaps/js-marker-clusterer (or remove one or the other). This is all very confusing.

For instance https://github.com/googlemaps/js-marker-clusterer/pull/75 and https://github.com/googlemaps/js-marker-clusterer/pull/78 are not in this repository. Also version numbers are different.

**Comment by grrowl** [comment]
I would much rather prefer https://github.com/googlemaps/js-marker-clusterer was archived and linked to this repo. It's more out of date, not maintained (or at least not officially), while this repo is receiving pull requests.

**Comment by stephenmcd** [comment]
Thanks, I've done that here: https://github.com/googlemaps/js-marker-clusterer/commit/06be139ba778ce5d59e7837ac2279631f4b439c6
