### ISSUE TITLE
Overlapping Infobox in Google Map

### ISSUE THREAD

**Issue by sagarwasule** [googlemaps/v3-utility-library#350]
Hi,

I'm facing an issue where there are multiple markers the infobox attached to the markers are over lapping each other. Could please let me know in case there is any workaround to resolve this issue.
Thanks

**Comment by stephenmcd** [comment]
Can you provide a sample that demonstrates the issue?

**Comment by sagarwasule** [comment]
![untitled](https://cloud.githubusercontent.com/assets/4396175/17239486/1db7f020-5582-11e6-9185-edca46641846.png)

**Note : Info masked for security reason
As you can find here the markers are having infobox overlapped. I need this to spread out by default so that the info can be view without overlapping.

**Comment by sagarwasule** [comment]
@stephenmcd Any suggestion/opinion/feedback to resolve this issue ?

**Comment by stephenmcd** [comment]
Sorry, I meant a code sample, not a screenshot.
