### ISSUE TITLE
MarkerClustererPlus does not hide marker InfoBoxes

### ISSUE THREAD

**Issue by tymarats** [googlemaps/v3-utility-library#358]
When an InfoBox is bound to a marker, MarkerClustererPlus does not hide it when it "collects" the marker. 

Fiddle: http://jsfiddle.net/tymarats/kmdjr4e6/2 

**Steps to reproduce:** 
Zoom out the map. InfoBoxes should be hidden when the markers disappear, but they are not.

Possible solution given in https://github.com/googlemaps/v3-utility-library/pull/356

**Comment by stephenmcd** [comment]
#356
