### ISSUE TITLE
`removeMarkers` doesn't remove all markers

### ISSUE THREAD

**Issue by fatshotty** [googlemaps/v3-utility-library#360]
Hi,
I try to remove all markers in MarkerCluster, but it doesn't remove all of them.

I think problem could be around this line of code

https://github.com/googlemaps/v3-utility-library/blob/master/markerclusterer/src/markerclusterer.js#L517

It loops in `markers` array incrementing the `i` index, but in `removeMarker_` function it performs a `splice` that changes the length of the array and, then, its indexes.
That causes not all markers will be removed.

Is it only me?

Thanks in advance

**Comment by patros** [comment]
I tried reproducing the issue your describing and couldn't. I can see what you mean about the splice, have you got a simple example to reproduce your issue?

**Comment by fatshotty** [comment]
Hi,
problem is related to `removeMarkers` function. Try
```js
markerClusterer.removeMarkers( markerClusterer.getMarkers() )
```

Fabio

**Comment by stephenmcd** [comment]
#367
