### ISSUE TITLE
Labels overlapping (z-index problem)

### ISSUE THREAD

**Issue by theredled** [googlemaps/v3-utility-library#375]
![capture d ecran 2017-08-12 a 13 38 37](https://user-images.githubusercontent.com/1306435/29240354-b2f257d2-7f63-11e7-9808-fd3c55bf8d23.png)

As you can see above, "all labels" seem to be on z-top of "all markers" which leads to a problem where labels are overlapping each others, and are visible when they should be hidden behind z-upper markers...

Am I missing something ?
Or is it an unfixable issue ?

Many thanks

**Comment by robertlayton** [comment]
It looks like, by default that the markers all have one z-index and the labels are just above that, hence the overlapping.

I fixed this locally, by just ensuring the markers themselves have specified z-indexes (I used `100 + (2 * number`), where number is the marker's index).
