### ISSUE TITLE
Dragging a RichMarker drags the map in the same time - Firefox

### ISSUE THREAD

**Issue by claudiupelmus** [googlemaps/v3-utility-library#378]
Demo link or sample code:
https://www.screencast.com/t/XyZEyu2rASma

What steps will reproduce the problem?
1. The map instance should have the 'draggable' property set to 'true' or not set at all
2. Go to Firefox
3. Start dragging a RichMarker marker instance

Expected result:
The map should not be dragged, but only the RichMarker marker

Actual result:
The map gets dragged together with the RichMarker marker

Version: latest

Browser / Operating System:
Tested on Firefox 55.0.3

Additional comments:
It seems to have something to do with how the 'addDomListener' is handled in terms of order/timing.
Even thought the library sets the map 'draggable' property to 'false' on marker's 'dragstart' event, it only takes effect the next time when you perform a RichMarker drag action, thus meanwhile making the map to be dragged as well.

**Comment by shamalli** [comment]
Same problem, 57.0.2 (64)

**Comment by claudiupelmus** [comment]
Hi @shamalli, I will fix this in the upcoming week.

**Comment by shamalli** [comment]
Hello, thanks, this would be great. Will be waiting.
