### ISSUE TITLE
Is there some kind of specification for the cluster image?

### ISSUE THREAD

**Issue by HubKing** [googlemaps/v3-utility-library#384]
I used the blue circle image that I got from Google's native Google Map clustering project's resource. When the cluster is loaded, the image is tiled. That is, there is one full circle at the top left, and three partial circles on the right, bottom and right bottom corner.

I checked the size, and its size was 40 * 40. The image in this project's example was 53 * 52. What is this, am I supposed to use exactly 53 * 52 size images? Otherwise, how can I remove this tiling effect?

**Comment by daytonmills** [comment]
I was able to set the sizes to my custom image specifications manually by editing this line in the markerclusterer.js

`this.sizes = [53, 56, 66, 78, 90];`

**Comment by garylittleRLP** [comment]
When using MarkerClustererPlus, use this command:

MarkerClusterer.IMAGE_SIZES = [53, 56, 66, 78, 90]; // array of cluster image widths
