### ISSUE TITLE
zIndex of map label has no effect if it's used with GeoJSON layer

### ISSUE THREAD

**Issue by Xyroid** [googlemaps/v3-utility-library#386]
I am using map label to display some property from GeoJSON data on GeoJSON layer. The layer has some dark color and the label is being created behind the GeoJSON data layer due to that the map label looks blurry. I tried to apply bigger zIndex for label than data layer but it has no effect. Check out the issue in plunker.

https://plnkr.co/edit/KvhIoRoibsbKk9e4k1Ch?p=preview

**Comment by marlonnardi** [comment]
To resolve, edit the maplabel.js, add at the end of the method
`MapLabel.prototype.onAdd = function()`

The following code:
`if (canvas.parentNode != null) {
    canvas.parentNode.style.zIndex = style.zIndex;
  }`
