### ISSUE TITLE
MarkerClusterPlus : Broken examples

### ISSUE THREAD

**Issue by bzah** [googlemaps/v3-utility-library#389]
The examples available at https://htmlpreview.github.io/?https://raw.githubusercontent.com/googlemaps/v3-utility-library/master/markerclustererplus/docs/examples.html seem to be broken.

I have this error on Chrome & Firefox : 
`Uncaught ReferenceError: google is not defined     at ?https://raw.githubusercontent.com/googlemaps/v3-utility-library/master/markerclustererplus/examples/simple_example.html:23`

**Comment by patros** [comment]
Looks like a simple mixed content issue. This works...
[http://htmlpreview.github.io/?https://raw.githubusercontent.com/googlemaps/v3-utility-library/master/markerclustererplus/examples/simple_example.html](http://htmlpreview.github.io/?https://raw.githubusercontent.com/googlemaps/v3-utility-library/master/markerclustererplus/examples/simple_example.html)
but this does not...
[https://htmlpreview.github.io/?https://raw.githubusercontent.com/googlemaps/v3-utility-library/master/markerclustererplus/examples/simple_example.html](https://htmlpreview.github.io/?https://raw.githubusercontent.com/googlemaps/v3-utility-library/master/markerclustererplus/examples/simple_example.html)
