### ISSUE TITLE
Is this even maintained??

### ISSUE THREAD

**Issue by teo1978** [googlemaps/v3-utility-library#392]
The first thing I did was to look at some examples and docs like
https://github.com/googlemaps/v3-utility-library/blob/master/geolocationmarker/examples/mylocation.html
https://github.com/googlemaps/v3-utility-library/blob/master/geolocationmarker/docs/reference.html

The html code is full of broken links, both in documentation text like 
```
See the <a href="https://google-maps-utility-library-v3.googlecode.com/svn/trunk/geolocationmarker/examples/mylocation.html">example</a>.
```
 and in actual script and css tags, e.g.
```
<script src="//google-maps-utility-library-v3.googlecode.com/svn/trunk/geolocationmarker/src/geolocationmarker-compiled.js"></script>
```

which makes me wonder: is this a dead project that is not even being maintained?

If so, you are **seriously** doing more harm than good by leaving this published on GitHub with a readme that actually says:
>We're comfortable enough with the stability and features of the libraries that we want you to build real production applications on it

At least replace that with a gigantic warning that this code is abandoned and doesn't work.

**Comment by stephenmcd** [comment]
Thanks for bringing this up. The library is still being maintained. You came across some bugs due to our migration from the old code.google.com site some time ago that were overlooked. I've attempted to clean all these up so the examples should be working now.
