### ISSUE TITLE
Clusters not responding to clicks/taps in Safari on iPad

### ISSUE THREAD

**Issue by rgsamways** [googlemaps/v3-utility-library#395]
Hello all,

Just wondering if any recents updates were made that would cause clusters to not respond to clicks/taps in Safari on the iPad. Getting several complaints this morning from users of our app saying similar issues.

Any help/advice appreciated.

Thanks..
Robin

**Comment by Valachio** [comment]
Same issue here.  The `click` event is not responding to touch click events.

As a temporary fix, I switched my Google Maps version to the release version rather than the experimental version.

**Comment by rgsamways** [comment]
Got it. Thank you.

**Comment by garylittleRLP** [comment]
The new experimental release is certainly "challenging". MarkerClustererPlus does work with macOS and Windows, but definitely not with iOS. (On my 5 year old iPad, I also can't pan the map -- of course, it uses an old unsupported version of iOS. But still, it's always worked before.) I'll have to try Android tomorrow.  I've tried to troubleshoot with no success -- I'll call it a Google bug for now and report it. Many sites use MarkerClustererPlus (or its predecessor MarkerClusterer -- written by Google itself) so it's certainly in their interest to solve this problem.

**Comment by garylittleRLP** [comment]
To clarify what's happening when running iOS 9.3.5 (the last version available for my 5 year old iPad), I've just discovered that the map can be panned but that I need to use two fingers to do so. When using earlier versions of the Google Maps JavaScript API I could pan with a one-finger drag on this device. One-finger panning still works as expected on my iPhone running iOS 11.2.5. On neither device will a click get through to a cluster icon.

**Comment by garylittleRLP** [comment]
By the way: the iOS 9.3.5 panning bug when using the GM 3.32 experimental release is NOT related to the marker clusterer click problem. I have another map that won't pan properly and it doesn't use the clusterer.

**Comment by garylittleRLP** [comment]
Bug reported to Google:

https://issuetracker.google.com/issues/73571522

**Comment by Valachio** [comment]
@garylittleRLP Thanks for your continued contribution to this project Gary.  We are using markerclusterplus  for our project and it has worked perfectly.

For Android devices (I'm using LG G4), there is no panning issues, so perhaps the panning issue is limited to Apple devices only?  The touch click seems to impact all touch devices though.

**Comment by garylittleRLP** [comment]
There are no panning issues with recent versions of iOS, just that old version on my iPad that I can't upgrade.

Please go to the Google bug report and star the issue. The more people who get involved the better.

On the positive side, all these issues have forced me (finally) to learn Github so I'm now posting up to date versions of all my libraries (InfoBox, KeyDragZoom, MarkerClustererPlus, and MarkerWithLabel).

**Comment by garylittleRLP** [comment]
I have verified that the "click" problem also is observed on Android.

**Comment by Valachio** [comment]
@garylittleRLP I starred the issue.  Thanks for writing the report

**Comment by Fausto-theXS** [comment]
It looks like the update now breaks the touch on Android, in both version 3.31 and 3.32
It was working for me before on version 3.31

Is it working for you on Android?

**Comment by garylittleRLP** [comment]
Here's what happened: the fix is only fo 3.32 exp, it breaks 3.31 (I'm working on a revised fix as a result.

Then yesterday Google updated the API and broke the clusterer (and lots of other code) again.

Hang in there. At the moment I'm unable to use 3.32 exp at all because of excessive idle events.

**Comment by jacquesdev** [comment]
Thanks @Valachio - I did not even realise I was using the experimental version, but have now switched it to the release version instead and it works great!

**Comment by Valachio** [comment]
Thank @garylittleRLP .  He's the one solving the problem with the Google team [here](https://issuetracker.google.com/issues/73571522)

**Comment by garylittleRLP** [comment]
I've just requested a pull for a version of MarkerClustererPlus that works with the experimental release of the API and with earlier versions.

**Comment by stephenmcd** [comment]
This is merged now - please re-open if this resurfaces.

**Comment by thelonewolf** [comment]
iOS 11.4 with GM 3.32 still an issue while using MarkerClusterPlus 2.1.1.

GM 3.31 cluster click event triggers but so does the map click event. On desktop only the cluster click event is triggered. The extra event being triggered can be a problem if you have actions setup to take place on that event.

Does upgrading to MCP 2.1.9 fix this issue?
