### ISSUE TITLE
click handler not executing

### ISSUE THREAD

**Issue by scotch83** [googlemaps/v3-utility-library#401]
If we have unclustered markers showing close enough to a cluster, clicking on the cluster executes the underlying marker's click handler because of their higher zIndex

**Comment by jeudywr** [comment]
I'm using this library along with angularjs-google-maps (https://github.com/allenhwkim/angularjs-google-maps) for me, the click on the clusters won't work at all.

**Comment by scotch83** [comment]
solved in issue #402
