### ISSUE TITLE
Uncaught TypeError: Cannot read property 'removeChild' of null. bug in 1.2 version

### ISSUE THREAD

**Issue by dexion** [googlemaps/v3-utility-library#404]
After update to version 1.2 I get `Uncaught TypeError: Cannot read property 'removeChild' of null` when I zoom map (marker delete for clustering)

**Comment by garylittleRLP** [comment]
Try using MarkerClustererPlus.

**Comment by atulgoswami21** [comment]
i have to surround with try catch. Now Clustering works perfect.

**Comment by dexion** [comment]
MarkerClustererPlus have same issue. I add check on null before function

23 февр. 2018 г. 8:38 ПП пользователь "atulgoswami21" <
notifications@github.com> написал:

i have to surround with try catch. Now Clustering works perfect.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/googlemaps/v3-utility-library/issues/404#issuecomment-368011007>,
or mute the thread

**Comment by nayv** [comment]
#393 contains a fix for this, but was taken out by a merge. @garylittleRLP commented he'll commit the fix again.

**Comment by garylittleRLP** [comment]
I've already made the pull request, just waiting for it to be processed.

**Comment by stephenmcd** [comment]
Merged now - thanks everyone.
