### ISSUE TITLE
Calling MarkerClusterer fitMapToMarkers() hides the clusters if the map is already fit to markers

### ISSUE THREAD

**Issue by Fausto-theXS** [googlemaps/v3-utility-library#407]
The best way to reproduce this behavior is by calling MarkerClusterer fitMapToMarkers() function twice.

The first time it works as expected, it fits the map to the bounds of the markers managed by the clusterer.

The second time, the clusters disappear from the map.

Thanks in advance for your support on this
Fausto

EDIT (2018-03-02)

Trying to find the root of this issue, by reviewing the code of MarkerClusterer Plus (MCP)
I guess it should be trivial, but definitively not for me, to fix

In the following function:

```
MarkerClusterer.prototype.fitMapToMarkers = function () {
  var i;
  var markers = this.getMarkers();
  var bounds = new google.maps.LatLngBounds();
  for (i = 0; i < markers.length; i++) {
    bounds.extend(markers[i].getPosition());
  }

  this.getMap().fitBounds(bounds);
};
```

Just after the call to fitBounds, the clusters_ becomes an empty array

The same code works fine with the original MarkerClusterer (MC) library, using a "similar" function

I only see some differences around the `this` scope between the two libraries, that might cause the issue, but I have no idea how
- MCP doesn't have the MarkerClusterer.prototype.getMap function, but it uses it in fitMapToMarkers

EDIT (2018-03-03)

The issue is related with the zoom_changed listener and the fact that Google Api triggers this event on fitBounds even if the zoom has not actually changed

This issue is avoided by checking if the zoom has actually changed before calling resetViewport_, as it's done by the original MC library

**Comment by stephenmcd** [comment]
#409
