### ISSUE TITLE
Markers not show in QWebView 

### ISSUE THREAD

**Issue by juancho137** [googlemaps/v3-utility-library#408]
I used Python 2.7 Shell to execute a code wich show a frame whit a browser... this browser show google maps. Code...
`        var marker = new google.maps.Marker({
          icon: 'https://www.tranzity.com/wp-content/uploads/2017/10/llamada-telefonica.png',
          position: myLatLng,
          map: map,
          title: 'Hello World!'
        });
`
but marker not appear. 

I tried using differents API versions (ex. v=3.31, v=3.30).... I get the same result... the marker not appear

Web inspector console (QWebInspector) register one error in marker.js line 1522, into de function _FW.prototype.Fa = function ()_

> Va: this.D.bind(this)
TypeError: 'undefined' is not a function (evaluating 'this.D.bind(this)')

But.... same error appear if I delete the code where marker is created. Therefore, I don't know if this error is the reason because the marker not appear. 

Some idea to resolve this problem?

**Comment by cleebp** [comment]
Just wanted to say that I am also not able to load markers in a QWebView, version 3.29 used to work but is no longer available as far as I know so I'm stuck.
