### ISSUE TITLE
setPosition on a single marker triggers setContent for all markers

### ISSUE THREAD

**Issue by AbijeetP** [googlemaps/v3-utility-library#412]
In one of the applications I'm working on, based on the last known speed of a vehicle, I'm interpolating the next position of the vehicle every 100 ms and plotting it on the map. This is causing a performance issue on mobile devices. 

We're also using MarkerWithLabels to put a label next to the Marker 

While running the performance profiler, I noticed that `setContent` inside MarkerWithLabels was executing a lot of times and was causing large layout redraws.

[![Performance Tab][1]][1]

----------

[![Source Tab][2]][2]

Putting a `console.log` revealed that it was being called for all the markers that we had even though we were only changing the position of only one of them. 

I reproduced this issue in a Codepen here - https://codepen.io/anon/pen/XZwGGr?editors=0011 

Short piece of relevant code,

    var i = 0.002;
    setInterval(function() {
        dynamicMarker.setPosition(new google.maps.LatLng(-33.91627341958452 + i, 151.23648314155578 +i));
        i = i + 0.001;
        console.log('----------**----------');
    }, 3000);

Marker creation,

     var tempMarker = new MarkerWithLabel({
            map: map,
            animation: google.maps.Animation.DROP,
            position: positions[i],
            icon: markerIcon,
            labelContent: i.toString(),
            labelAnchor: new google.maps.Point(18, 12),
            labelClass: "my-custom-class-for-label", // the CSS class for the label
            labelInBackground: true
        });

I'm updating the position of a *single* marker every 3 seconds. I've also modified the `setContent` function of MarkerWithLabels inside the HTML section. If you open the console, you'll see `setContent` printed along with the content. You'll notice that this happens for all the markers that we've added and not just the marker being updated.

Is this common? Is this how it is supposed to behave?

  [1]: https://i.stack.imgur.com/WtkOd.png
  [2]: https://i.stack.imgur.com/XFWVt.png

Ref: https://stackoverflow.com/q/49115083/903324

**Comment by stephenmcd** [comment]
Sounds good - would you like to create a pull request with the fix?

**Comment by AbijeetP** [comment]
@stephenmcd - Sure, I'll do that.
