### ISSUE TITLE
Scale ratio between zoom levels must be 2

### ISSUE THREAD

**Issue by MaticDiba** [googlemaps/v3-utility-library#414]
I'm trying to access open WMTS that uses different CRS. This is map servers address: http://gis.arso.gov.si/arcgis/rest/services/Lidar_hillshade/MapServer

Custom CRS is not a problem. I registered new CRS with:
` gmaps.ags.Util.registerSR(102060,'PROJCS["MGI / Slovene National Grid",GEOGCS["MGI",DATUM["D_MGI",SPHEROID["Bessel_1841",6377397.155,299.1528128]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",15],PARAMETER["scale_factor",0.9999],PARAMETER["false_easting",500000],PARAMETER["false_northing",-5000000],UNIT["Meter",1]]'); `

The issue is, that apparently it uses different zoom levels that are not supported by GMaps? Is there a workaround for this issue?

Error I'm getting:

> Uncaught Error: This type of map cache is not supported in V3. 
> Scale ratio between zoom levels must be 2
>     at new Projection (arcgislink.js:3077)
>     at TileLayer.init_ (arcgislink.js:3196)
>     at MapService.<anonymous> (arcgislink.js:3183)
>     at MapService.<anonymous> (js?sensor=false:117)
>     at trigger (js?sensor=false:115)
>     at triggerEvent_ (arcgislink.js:206)
>     at MapService.setLoaded_ (arcgislink.js:1946)
>     at arcgislink.js:1929
>     at Object.jsonpcallback (arcgislink.js:792)
>     at legend?callback=ags_jsonp.ags_jsonp_2_249908&f=json:1

**Comment by patros** [comment]
Can you create a static html page that reproduces this and I'll take a look?

**Comment by MaticDiba** [comment]
Hi,
live example is here: http://dibatista.com/gmaps/examples/mercator2.html

Thanks.

**Comment by patros** [comment]
I was hoping there would be a quick win I could come up for you @MaticDiba but I think you'll need to use another mapping library or republish that map layer yourself with the right LOD resolution ratios.
