### ISSUE TITLE
Proposal to update addMarkers

### ISSUE THREAD

**Issue by kcudnik** [googlemaps/v3-utility-library#421]
Consider changing https://github.com/googlemaps/v3-utility-library/blob/master/markerclusterer/src/markerclusterer.js#L412
`else if (Object.keys(markers).length) {`
to
`else if (Object.keys(markers).length && !Array.isArray(markers)) {`

since array could have some user properties defined, and when array is empty it will be interpreted as object and properties will be interpreted as markers

**Comment by patros** [comment]
If you look at the commit for that line it seems that is the intention... https://github.com/googlemaps/v3-utility-library/issues/266

**Comment by kcudnik** [comment]
thanks for info!
