### ISSUE TITLE
ArcGIS Link MapOverlay show() & hide() error

### ISSUE THREAD

**Issue by gavinharriss** [googlemaps/v3-utility-library#424]
When calling the show() & hide() methods on gmaps.ags.MapOverlay an error occurs:

```
Uncaught TypeError: Cannot read property 'style' of null
    at MapOverlay.show (arcgislink.js:3671)
    at mapapp.layer.Providers.ArcGIS.showLayer (mapapp-layer-providers-arcgis.js:25)
```

```
Uncaught TypeError: Cannot read property 'style' of null
    at MapOverlay.hide (arcgislink.js:3679)
    at mapapp.layer.Providers.ArcGIS.hideLayer (mapapp-layer-providers-arcgis.js:30)
```

Problem is because internal this.div_ property is null.

Workaround is to use overlay.setMap(map) to show, and overlay.setMap(null) to hide.

**Comment by patros** [comment]
That's an odd one. The standard map overlay api is to use setMap(null) to hide an overlay. And looking at the code the div_ is only set for image overlays. Do you have a simple html file that I can use to reproduce this?

**Comment by gavinharriss** [comment]
Sorry, no test file available. I'll put one together when get a bit of spare time. In a mad scramble to port my code over to Leaflet as the new Google Maps Platform is going to cost me a small fortune! :(

**Comment by patros** [comment]
Yeah, know what you mean @gavinharriss. I've used it extensively and now need to figure out what it's going to cost :(
