### ISSUE TITLE
Markercluster suggestion - enable text and link when marker represents just one point

### ISSUE THREAD

**Issue by HealingRooms** [googlemaps/v3-utility-library#426]
The Markercluster utility is very helpful for a large number of points (over 31) compared to the generic Google Maps API, but it is limited in that it can ONLY provide a visual representation of the locations.  It CANNOT yet serve to connect the viewer to the contact information of each point or redirect to a URL.

Currently, the markers array only uses fields such as this:
`{lat: -33.718234, lng: 150.363181},`

Other map API scripts do enable the display of text (versus just a pin) and a link, using two arrays... well, perhaps three now with the latitude and longitude.

`  <textarea><?php echo $markers; ?></textarea>
  <textarea><?php echo $infoWindowContent; ?></textarea>`

This is using a value such as the following:

`$markers .= "['" . $city . ' ' . $state . "', " . $latitude . ", " . $longitude . "]";`
        
```
$infoWindowContent .=  "['<div class=" . '"' . "info_content" . '"' . ">' +
'<h3>" . $city . ' ' . $state . "</h3>' +
'<p>Blahde blah blah.</p>' +        '</div>']";
```

The limitations of those other Google maps API tools is that they always display... even when the low zoom level causes the text to be overlapping, illegible, and unusable.

I would recommend that the Markcluster utility make use of additional fields to represent the display of text or HTML code (with or without clicking or hovering) and/or a hyperlink to use when clicking the pin.

The text could display when a pin only represents one location (the level 0), or showing the first character in the "labels" array.

`var labels = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';`

...or using just one standard character, "1" in this case:

`var labels = '1';`

**Comment by stephenmcd** [comment]
Presumably you're populating markers in a for-loop with locations that have extra data, in which case it's fairly straightforward to do whatever you like with the click event of the marker, like assigning a tooltip. 

There's a good example here: https://github.com/googlemaps/property-finder/blob/68e8e6b3c0e3af54f3e3089d3bed0b5d4b75b561/realty/static/js/app.js#L113-L162

Given how simple this is, it's beyond the scope of marker clusterer to handle this for you, since there wouldn't be a "one size fits all" solution.

**Comment by HealingRooms** [comment]
Thank you for providing an example with your "property finder" app, especially with the html that could be appended to a "markers" array.

Someone else had suggested (on another post) to try the "plus" version of this api, called the "MarketClusterPlus".  Unfortunately, the documentation was identical to the slightly simpler MarketCluster app, and had no additional descriptive text fields or URL fields.

It would seem that to create additional HTML to display (such as an image of the property or a link to additional information) would require making a completely separate utility, such as you have done with the Property Finder.  How unfortunate.

**Comment by garylittleRLP** [comment]
MarkerClustererPlus allows you to replace the default calculator (which returns info about the icon and text to be used) with anything you like. One of the properties a calculator returns is "text" which is normally the count but it can be anything you like -- including HTML markup -- whatever you provide, it's simply assigned to the innerHTML of its container. Give it a try and let me know how it works.

I spent a lot of time on the documentation for MarkerClustererPlus. The specs for a custom calculator are all there.

Gary

**Comment by HealingRooms** [comment]
Hi Gary,

Are you referring to the examples.html and reference.html files in the docs folder of the MarkerClusterPlus project?

This is the folder: https://github.com/mahnunchik/markerclustererplus/tree/master/docs
These are the two files:
https://github.com/mahnunchik/markerclustererplus/blob/master/docs/examples.html
https://github.com/mahnunchik/markerclustererplus/blob/master/docs/reference.html

The only URL fields seem to be for the standard pin icon.

In the examples, the pins are only for displays, and do not include the "text" you mentioned (and which Stephen has an equivalent of in his real estate project).

In the standard code, there's just a simplified lat/long array, such as the last "**var locations**" part of this sample script:

```
    <style>
      #map {
        height: 100%;
      }
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
<div id="map"></div>
    <script>
      function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 3,
          center: {lat: -28.024, lng: 140.887}
        });

        var labels = '1';

        var markers = locations.map(function(location, i) {
          return new google.maps.Marker({
            position: location,
            label: labels[i % labels.length]
          });
        });

        var markerCluster = new MarkerClusterer(map, markers,
            {imagePath: 'https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m'});
      }
}
var locations = [
        <?php
    $markers = '{lat: -31.563910, lng: 147.154312},';
    $markers .= '{lat: -33.718234, lng: 150.363181},';
    $markers = '{lat: -43.999792, lng: 170.463352';
         echo $markers; 
?>
]   
</script> 
```

-Bryce

**Comment by HealingRooms** [comment]
I do see some samples in the speed_test.js file (a speed test example, of all things?), starting at line 96, which makes use of the data array from the data.json file.

```
speedTest.markerClickFunction = function(pic, latlng) {
  return function(e) {
    e.cancelBubble = true;
    e.returnValue = false;
    if (e.stopPropagation) {
      e.stopPropagation();
      e.preventDefault();
    }
    var title = pic.photo_title;
    var url = pic.photo_url;
    var fileurl = pic.photo_file_url;

    var infoHtml = '<div class="info"><h3>' + title +
      '</h3><div class="info-body">' +
      '<a href="' + url + '" target="_blank"><img src="' +
      fileurl + '" class="info-img"/></a></div>' +
      '<a href="http://www.panoramio.com/" target="_blank">' +
      '<img src="http://maps.google.com/intl/en_ALL/mapfiles/' +
      'iw_panoramio.png"/></a><br/>' +
      '<a href="' + pic.owner_url + '" target="_blank">' + pic.owner_name +
      '</a></div></div>';

    speedTest.infoWindow.setContent(infoHtml);
    speedTest.infoWindow.setPosition(latlng);
    speedTest.infoWindow.open(speedTest.map);
  };
};
```

From data.json:

```
var data = { "count": 10785236,
 "photos": [{"photo_id": 27932, "photo_title": "Atardecer en Embalse", "photo_url": "http://www.panoramio.com/photo/27932", "photo_file_url": "http://mw2.google.com/mw-panoramio/photos/medium/27932.jpg", "longitude": -64.404945, "latitude": -32.202924, "width": 500, "height": 375, "upload_date": "25 June 2006", "owner_id": 4483, "owner_name": "Miguel Coranti", "owner_url": "http://www.panoramio.com/user/4483"}
,
{"photo_id": 522084, "photo_title": "In Memoriam Antoine de Saint Exupéry", "photo_url": "http://www.panoramio.com/photo/522084", "photo_file_url": "http://mw2.google.com/mw-panoramio/photos/medium/522084.jpg", "longitude": 17.470493, "latitude": 47.867077, "width": 500, "height": 350, "upload_date": "21 January 2007", "owner_id": 109117, "owner_name": "Busa Péter", "owner_url": "http://www.panoramio.com/user/109117"}
,
```

**Comment by garylittleRLP** [comment]
There is no example showing how to implement your own calculator, but here is the description of how to do it (from the comments in MarkerClustererPlus):

[The "calculator" property is a] function used to determine the text to be displayed on a cluster marker and the index indicating which style to use for the cluster marker. The input parameters for the function are (1) the array of markers represented by a cluster marker and (2) the number of cluster icon styles. It returns a ClusterIconInfo object. The default calculator returns a text property which is the number of markers in the cluster and an index property which is one higher than the lowest integer such that 10^i exceeds the number of markers in the cluster, or the size of the styles array, whichever is less. The styles array element used has an index of index minus 1. For example, the default calculator returns a text value of "125" and an index of 3 for a cluster icon representing 125 markers so the element used in the styles array is 2. A calculator may also return a title property that contains the text of the tooltip to be used for the cluster marker. If title is not defined, the tooltip is set to the value of the title property for the MarkerClusterer. The default value is MarkerClusterer.CALCULATOR.

Since the calculator has access to an array of all the markers that are represented by the cluster marker, you can get very creative. The "text" result can be anything you like, a <div>, <img>, or just plain text.

**Comment by garylittleRLP** [comment]
Bug in GitHub, that last sentence should end with "div, img, or just plain text". (You can't use less than or greater than in comments apparently).

**Comment by HealingRooms** [comment]
Thank you for the link from jarkerclusterer.js line ~622.

**Comment by HealingRooms** [comment]
Hmmm... Mistype?  

markerclusterer.js line ~622.

**Comment by garylittleRLP** [comment]
I just created a simple calculator, to show that it works with HTML results. I've replaced less than and greater than with brackets.

		var markerCluster = new MarkerClusterer(map, markers, {
			calculator: myCalculator
		});
      
		function myCalculator(markers, numStyles) {
	
			return {
				 text: "[a href='http://www.GaryLittle.ca/' target='_blank']" + markers.length + "[/a]"
				,index: 1
				,title: ""
			};
		}

**Comment by HealingRooms** [comment]
Thank you for the example, Gary.
I seem to be making some progress, and I anticipate being able to resume next Thursday.

I paused at a point where the photo_file_url path seemed to be unable to use the google maps static image path, such as 
http://maps.googleapis.com/maps/api/staticmap?&zoom=10&size=250x150&maptype=roadmap&sensor=false&markers=color:blue%7Clabel:S%7C36.741676,-88.643047

![2018-05-17_160223](https://user-images.githubusercontent.com/6922639/40207924-c700a78e-59eb-11e8-8014-f91210185648.png)

**Comment by garylittleRLP** [comment]
A key is probably now required for the static map API and the sensor parameter is no longer required.
