### ISSUE TITLE
Importing markerclusterer as npm package

### ISSUE THREAD

**Issue by nanomosfet** [googlemaps/v3-utility-library#427]
I use webpack to bundle my js files and also so that I don't have global variables. This requires that each package is to be a node js package(npm). 

Is there anyway we can make some of these utilities such as markerclusterer to be importable by npm?

Currently there are some 3rd party libraries that do this but they all have an older version of the files.

**Comment by ericnewton76** [comment]
Indeed.  Would be nice to get just a thin package.json around the library and published to npm where it can be modularized.

**Comment by nanomosfet** [comment]
@ericnewton76 If you take a look at this [library](https://github.com/yuanqing/load-google-maps-api/) they have an interesting way of making an always up to date npm wrapper for the google maps api. I think we can do something similar for tools in this libary

**Comment by jameelmoses** [comment]
This would be a great feature to have

**Comment by stephenmcd** [comment]
I've pushed `markerclusterer` and friends to NPM in the following change: 2c83cf3b589a08d2755f8793c479428c394df4ef

Please try it out.
