### ISSUE TITLE
[MarkerClusterer/Plus] google maps v3.32 fitBounds issue with redrawing clusters

### ISSUE THREAD

**Issue by ping4tucker** [googlemaps/v3-utility-library#429]
Google maps is updating to a new map and a new render as their release version next week.  This change seems to break clustering when fitBounds is called on the map; the markers don't recluster and existing clusters don't join new clusters.

I think this is because when the zoom_change listener is fired during fitBounds, it is fired before the map has a new zoom level or when the map has completed zooming out.  Because of this, the clusters don't redraw.  I tried manually calling repaint after fitBounds, but that didn't seem to help (not sure why).

I ended up moving the logic from the zoom_change listener to the idle listener and that seemed to fix the issue.

**Comment by stephenmcd** [comment]
Could you create a pull request with your fix? Thank you.

**Comment by Fausto-theXS** [comment]
Do you mean with version 3.32?

I couldn't reproduce that issue on my side with 3.32
I am currently calling cluster repaint after map firBounds

**Comment by ping4tucker** [comment]
After trying to recreate the issue in a jsfiddle, it seems like the problem arises when the map is zoomed out all the way (I feel like I've read about about a bug where clustering doesn't work on the last zoom out of the map).  Setting a minZoom on the map seems to fix the issue.  Here is the jsfiddle:
http://jsfiddle.net/Lmm5hrp9/2/.  
Click the fitBounds button and it will zoom out all the way and markers won't cluster. I'm not sure if this is the same issue that I was seeing originally.  Let me know if I'm just doing something stupid.

**Comment by NumanHassan** [comment]
@ping4tucker by setting minZoom i am still not able to see markers as a clusters

**Comment by harrington101** [comment]
I'm still experiencing this problem. Has anyone found a solution? When I add out of bounds markers and then call fitbounds to zoom the map out there end up being hundreds of small marker clusters. I have 2 sets of markers but I'm only calling fitbounds on one of them.
