### ISSUE TITLE
Center changes after click on cluster when locations are very close to each other

### ISSUE THREAD

**Issue by fire2** [googlemaps/v3-utility-library#434]
Hi,
I am using the latest markerclusterer api (1.0.1) and initialising the clusterer with the default click and zoom options like this.

`var markerCluster = new MarkerClusterer(map, markers, {imagePath: clusterImagePath});
`
I am experiencing an issue when locations are very close to each other. I expect the map to fit in the cluster bounds as normally, however sometimes (not always but most of the times) it fits in the bounds correctly but immediately after moves and opens an infowindow from a location in the area (which is not any of the markers). 

Here are 2 short screencasts with different maps where you can see the issue:
https://www.screencast.com/t/8ofnIptll
https://www.screencast.com/t/voaCAc7g3N

What could be the issue here? If you need any other info please let me know.

**Comment by garylittleRLP** [comment]
Try MarkerClustererPlus and see if it makes a difference.

**Comment by fire2** [comment]
Thank you for your quick reply. I just gave it a try and I don't have the issue with MarkerClustererPlus, it is working correctly. So thank you for the solution!

It would be interesting to know what is causing this on the simple version.
