### ISSUE TITLE
Map not clustering on zoom out

### ISSUE THREAD

**Issue by sunderkasajal1203** [googlemaps/v3-utility-library#439]
I have a dataset of 100000 and i am sending in the patch of 10000 each while fetching the data i am adding the markers and redrawing the cluster so in the end i get a single cluster of 100000. But once i zoom in and try to zoom out again they overlap in patches of 10000 each instead reforming the single cluster of 100000.

 var mapDiv = document.getElementById('newmap');
           map = new google.maps.Map(mapDiv, {
 center: new google.maps.LatLng(latitude, longitude),
 zoom: 3,
 panControl: true,
 mapTypeControl: true,
 mapTypeControlOptions: {
         style: google.maps.MapTypeControlStyle.DROPDOWN_MENU
 },
 zoomControl: true,
 zoomControlOptions: {
         position: google.maps.ControlPosition.LEFT_TOP,

 },
 streetViewControl: true,
 mapTypeId: google.maps.MapTypeId.ROADMAP
         });
          function addMarker1(locations,outletname,outletData)
           {
            var infoWindow = new google.maps.InfoWindow();
            markers = locations.map(function(location, i)
            {
                 return new google.maps.Marker
                  ({
                    position: location,

                  });
            });
           markerCluster = new MarkerClusterer(map, markers,{imagePath: 'https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m'});

           new_arr=new_arr.concat(markers);
           markerCluster.clearMarkers()
           markerCluster.addMarkers(new_arr);
           markerCluster.redraw();

    }
    // this is sending data 10000 each
 for (var i = 0; i < outletDataLen; i++) {
 outletArray.push(outletData[i]['Outletview']['name']);
 j.push({
         lat: parseFloat(outletData[i]['Outletview']['latitude']),
         lng: parseFloat(outletData[i]['Outletview']['longitude'])
 });
 outletname.push(outletData[i]['Outletview']['name']);
 }
 addMarker1(j, outletname, outletData);

**Comment by LeeZ-2017** [comment]
Thank you for your support. I have solved this problem.

**Comment by sunderkasajal1203** [comment]
Hi What is the solution to this issue?
