### ISSUE TITLE
Issue using SVG icons when "enableRetinaIcons" is set to "false".

### ISSUE THREAD

**Issue by codespacing** [googlemaps/v3-utility-library#441]
I tried to use SVG icons instead of PNG images for the clusters. SVG icons are displayed only if i set "enableRetinaIcons" to "true". When set to "false", SVG icons are not displayed.

I think the problem is due to the usage of the [CSS property "clip"](https://developer.mozilla.org/en-US/docs/Web/CSS/clip) that is deprecated and no more supported by some browsers like "Google Chrome".

I made a simple test by changing the following code:

```
img = "<img src='" + this.url_ + "' style='position: absolute; top: " + spriteV + "px; left: " + spriteH + "px; ";
if (this.cluster_.getMarkerClusterer().enableRetinaIcons_) {
      img += "width: " + this.width_ + "px; height: " + this.height_ + "px;";
} else {
      img += "clip: rect(" + (-1 * spriteV) + "px, " + ((-1 * spriteH) + this.width_) + "px, " +
          ((-1 * spriteV) + this.height_) + "px, " + (-1 * spriteH) + "px);";
}
img += "'>";
```

to:

```
img = "<img src='" + this.url_ + "' style='position: absolute; top: " + spriteV + "px; left: " + spriteH + "px; ";
if (this.cluster_.getMarkerClusterer().enableRetinaIcons_) {
  img += "width: " + this.width_ + "px; height: " + this.height_ + "px;";
} else {
  img += "width: " + this.width_ + "px; height: " + this.height_ + "px;";
}
img += "'>";
```

and the SVG icons are now displayed. 

I found an alternative to the deprecated "clip" property which is "[clip-path](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path)" but i don't know how to use it.

Can you please check this issue and provide a solution if possible?

Thank you

**Comment by garylittleRLP** [comment]
I think the better workaround for the moment is to simply set enableRetinaIcons to true when using a SVG icon. This simply tells MarkerClustererPlus not to clip off a portion of a sprite. The only caveat is that you can't use SVG sprites (ie., icons made up of several images).

**Comment by codespacing** [comment]
The problem is that i'm using MarkerClustererPlus for a map application that gives the user the possibility to enable/disable Retina and also to change the default cluster PNG image. The user may not understand that they don't need to use retina with SVG icons, that's why i want to prevent any issue of that kind.

Another workaround i made is to check the image extension. If it's an SVG icon and that Retina was enabled, MarkerClustererPlus will ignore the clip option and display the image as it is. It work fine for me. Here's the changes i made to MarkerClustererPlus:

```
var ext = this.url_.substr( (this.url_.lastIndexOf('.') +1) );
img = "<img src='" + this.url_ + "' style='position: absolute; top: " + spriteV + "px; left: " + spriteH + "px; ";
if (this.cluster_.getMarkerClusterer().enableRetinaIcons_ || ext == 'svg') {
      img += "width: " + this.width_ + "px; height: " + this.height_ + "px;";
} else {
      img += "clip: rect(" + (-1 * spriteV) + "px, " + ((-1 * spriteH) + this.width_) + "px, " +
          ((-1 * spriteV) + this.height_) + "px, " + (-1 * spriteH) + "px);";
}
img += "'>";
```

Do you think i can add this as a "Pull request"?

Thank you
