### ISSUE TITLE
map.fitBounds for large circles positions outside the world map

### ISSUE THREAD

**Issue by Sanchokus** [googlemaps/v3-utility-library#443]
Hi,
The map doesn't fit bounds correctly for very large circles:

- Center on 5, 5
- Radius 4.5k km
- Positioning is far upper than it should be
http://jsfiddle.net/06hd8fvx/

![image](https://user-images.githubusercontent.com/10008426/42681317-a0a307d0-8687-11e8-89fe-5d57adfe5f99.png)

**Comment by stephenmcd** [comment]
Hi, this issue tracker is for the utility library, not the JS API itself - for that you should open an issue here: https://issuetracker.google.com/components/188853/manage#basic

Thanks
