### ISSUE TITLE
Touch on a clustererd marker and swipe, and the map does not scroll (unlike ordinary marker)

### ISSUE THREAD

**Issue by aoyama-val** [googlemaps/v3-utility-library#444]
Hi,

I know this is a really complicated issue stems from v3.32's incompatibility, but I hope someone will come up a better workaround someday...
(https://issuetracker.google.com/issues/73571522)

The Problem:
When you touch a not-clustered marker and swipe, the map scrolls, however, when you do the same on a clustered marker, the page itself scrolls, not the map.
This is easily reproducible with iPhone and the simple_example.html.
Also, I have confirmed that deleting the following part fixes the issue: (I believe this is not accetable though)

```
// March 1, 2018: Fix for this 3.32 exp bug, https://issuetracker.google.com/issues/73571522
// But it doesn't work with earlier releases so do a version check.
  if (gmVersion >= 332) { // Ugly version-dependent code
    google.maps.event.addDomListener(this.div_, "touchstart", function (e) {
      e.stopPropagation();
    });
  }
```

The issue makes it difficult for the user to scroll the map filled with many clustered markers.

**Comment by sre-nw-dev** [comment]
Adding on to this, occasionally with gestureHandling set to cooperative, swiping with two fingers where one finger is on a cluster marker and one finger is not somehow prevents the idle event from being triggered when you release the screen, so the clusters disappear but are not redrawn until you swipe again. This happens for both markerclusterer and mcplus.

**Comment by philip-firstorder** [comment]
Reproduced this today and will try to find the cause in markerclustererplus.
