### ISSUE TITLE
Wrong cluster overlapping

### ISSUE THREAD

**Issue by javor454** [googlemaps/v3-utility-library#448]
While using cooperative gesture handling, clusters overlap hint suggesting to use ctrl + scroll.
![overlap](https://user-images.githubusercontent.com/16645414/43718468-0bb02434-998b-11e8-836a-8ed0a592ea21.png)

**Comment by alexanderberner** [comment]
same problem here, it seems that the whole `div` containing the cluster icons gets the highes possible `z-index`

**Comment by dylanjameswagner** [comment]
I found a CSS workaround by setting `z-index: 4;` and `pointer-events: none;` on the overlay.
