### ISSUE TITLE
Performance issues after new rendering engine added

### ISSUE THREAD

**Issue by SteveDowsett** [googlemaps/v3-utility-library#451]
Since google have deprecated v3.31 we have been forced to use v3.33 of their javascript api, this is causing major issues with large sets of clusters using both markerclusterer and markerclustererplus. Id suspect it has something to do with the new rendering engine, but this is a serious issue for us as we now have the issue in production environments.

Any ideas?

**Comment by piehouserat** [comment]
Hey guys, anyone else experiencing severe performance issues with the markerclusterer plugin since the upgrade to 3.33? Exact same code as before but now can take up to a minute to re-draw the clusters after zooming in or out.

**Comment by garylittleRLP** [comment]
I use MarkerClustererPlus every day with the latest experimental release of GM and have not noticed a slowdown. Try it yourself at map.garylittle.ca

**Comment by Fausto-theXS** [comment]
I have no complains neither when using MarkerClustererPlus with version 3.33

**Comment by rohit-aneja** [comment]
I am not able to render 3000+ markers even with MarkerClusterer, the map is just too slow to pan and zoom.
