### ISSUE TITLE
Compass buttons in street view are of submit type.

### ISSUE THREAD

**Issue by istratos** [googlemaps/v3-utility-library#453]
As title says, the buttons for the compass in street view mode are not defined and thus treated as submit type by default. Please correct this to make them of `type="button"'`

Problem arises when the google map is inside a `<form>` causing it to submit accidentally when clicking in any of the compass' buttons.

Thanks.

**Comment by stephenmcd** [comment]
That's not related to this library - you probably want to use the issue tracker for the JavaScript API: https://issuetracker.google.com/components/188853
