### ISSUE TITLE
rawgit is in sunset phase

### ISSUE THREAD

**Issue by Hissvard** [googlemaps/v3-utility-library#455]
Like pointed out on the site itself, rawgit is currently in its sunset phase - in the process of shutting down in October 2019.
MarkerClusterer is currently using as a default resource to host its custom markers https://github.com/googlemaps/v3-utility-library/blob/2015e66cabec3a5553a4ef12c0ac9c332d7dbcc3/markerclustererplus/src/markerclusterer.js#L1639
so it might be appropriate to switch to something else.

**Comment by stephenmcd** [comment]
Thanks for the heads up
