### ISSUE TITLE
MarkerCluster: Unclusterize points which at the same place

### ISSUE THREAD

**Issue by rimlin** [googlemaps/v3-utility-library#464]
How i can unclusterize points, which is at the same place? I have situation, where i have several points with same lnglat values and this cluster cannot be unclusterized. Is there such a possibility to do it now?

**Comment by Fausto-theXS** [comment]
You can try something like OverlappingMarkerSpiderfier that combines well with markerclustererplus

**Comment by rimlin** [comment]
@Fausto-theXS thanks, will check it!

**Comment by ThorvaldAagaard** [comment]
How did your test go? I have tested OverlappingMarkerSpiderfier  but ended op dropping it due to performance

**Comment by rimlin** [comment]
In my case i solved the problem by use of simple `google.maps.InfoWindow`. If points is overlapped - it show info window about points which in one position.

Example:

```
  const infoWindow = new google.maps.InfoWindow();

  google.maps.event.addListener(_markerCluster, 'clusterclick', (cluster, event: Event) => {
    if (cluster.getMarkers().length > 1) {
      const markers = cluster.getMarkers();
      let isOverlappedCluster = true;

      markers.slice(1).reduce((prevMarker: google.maps.Marker, marker: google.maps.Marker) => {
        if (marker.getPosition().equals(prevMarker.getPosition()) === false) {
          isOverlappedCluster = false;
        }

        return marker;
      }, markers[0]);

      if (isOverlappedCluster) {
        infoWindow.setContent('markers info...');
        infoWindow.setPosition(cluster.getCenter());
        infoWindow.open(gmap);
      }
    }
```

**Comment by osthafen** [comment]
> In my case i solved the problem by use of simple `google.maps.InfoWindow`. If points is overlapped - it show info window about points which in one position.

Instead of showing an infoWindow you could move the marker a tiny bit:

```
if (isOverlappedCluster) {
                        
    markers[0].setPosition(new google.maps.LatLng(markers[0].getPosition().lat() + 0.0005, markers[0].getPosition().lng() + 0.0005))

}
```

**Comment by CoachMat10** [comment]
I used markerclustererplus, and for me this works:
google.maps.event.addListener(cMarkerClusterer, "clusterclick", function (c) {
            var markers = c.getMarkers();
            
            //Check Markers array for duplicate position and offset a little
            if (markers .length > 1) {
                //Check if all markers are in the same position (with 4 significant digits)
                if (markers .every((val, index, arr) => (val.getPosition().lat().toFixed(4) == arr[0].getPosition().lat().toFixed(4)) && (val.getPosition().lng().toFixed(4) == arr[0].getPosition().lng().toFixed(4)))) { /
                    //Don't modify first element
                    for (i = 1; i < cAllClusterMarkers.length; i++) {
                        var existingMarker = cAllClusterMarkers[i];
                        var pos = existingMarker.getPosition();                        
                        var quot = 360.0 / cAllClusterMarkers.length;
                        var newLat = pos.lat() + -.00008 * Math.cos(+a * i); //+ -.00008 * Math.cos((+quot * i) / 180 * Math.PI);  //x                        
                        var newLng = pos.lng() + -.00008 * Math.sin(+a * i);  //+ -.0008 * Math.sin((+quot * i) / 180 * Math.PI);  //Y
                        existingMarker.setPosition(new google.maps.LatLng(newLat, newLng));                        
                    }
                    let cZoom = map.getZoom();
                    map.setZoom(cZoom-1);
                    map.setZoom(cZoom+1);
                } 
            }            
        });
