### ISSUE TITLE
MarkerClustererPlus takes really long to paint large ammount of markers

### ISSUE THREAD

**Issue by J4cku** [googlemaps/v3-utility-library#465]
Is it just me or is MarkerClustererPlus takes long to paint large ammounts of markers. Not only that it adds markers to clusters kind of additively ? Like it takes it few steps and it paints 100, 300 , 500 in steps. I am talking about 20-30k of markers

**Comment by J4cku** [comment]
The thing is it starts after 2000 markers

**Comment by garylittleRLP** [comment]
You may want to try adjusting the values of the batchSize and batchSizeIE parameters to see if it helps. The defaults are 2000 and 500, respectively. Markers are created in batches to avoid timeout errors in some browsers; of course, these days, browsers are faster and more efficient, so you may get away with increasing the batch size.

**Comment by J4cku** [comment]
Under 2000 markers the show() method was called ex
