### ISSUE TITLE
SetCenter and show zoom till minimum 3 markers in map 

### ISSUE THREAD

**Issue by rabdavinci** [googlemaps/v3-utility-library#466]
Hi all!

The center of the map is users location coordinates. There are more than 3000 pins in the map and i use clustering.
Need zoom in or zoom out till show 3 markers. 

Any idea, please? 

Thank you all!

**Comment by amuramoto** [comment]
Please ask how-to questions on our StackOverflow tag:

https://stackoverflow.com/questions/tagged/google-maps-api-3
