### ISSUE TITLE
InvalidValueError: setMap: not an instance of Map; and not an instance of StreetViewPanorama

### ISSUE THREAD

**Issue by VikkiUser** [googlemaps/v3-utility-library#467]
Have a google map object with that `name: "Pg"` in constructor, (in InfoBox right before error comes) and error text in issue header
var theMap outside the init map func.
`theMap = new google.maps.Map(document.getElementById('map'), mapOptions);` // exactly init map obj
Map use InfoBox latest code and MarkerClusterer lib.
When click on marker error appear.
Can anyone help?

P.S. If google maps loading twice on same page can that cause the problem?

**Comment by gabrielbusarello** [comment]
Someone solved that error?

**Comment by jpoehnelt** [comment]
Reproducible example?
