### ISSUE TITLE
Adding labels to MarkerClustererPlus

### ISSUE THREAD

**Issue by Valachio** [googlemaps/v3-utility-library#468]
For a standard Google Maps marker, I can create a label below the marker with the following code:

```
var marker = new google.maps.Marker({
    label: {
        text: '$2.15m',
        color: 'black',
    }
    ... other markers attributes
})
```

The result looks [like this](https://i.gyazo.com/aeb9b24058936a72b81cda5fc61bdc3d.png).

However, when the marker gets rolled up into a markercluster, the label disappears.

Is there some way to display a label for each markercluster, customizable depending on the content of the markerclusterer (the markers inside the markercluster)?

**Comment by garylittleRLP** [comment]
You might be able to do this by using a custom calculator. You could certainly use a custom calculator to display a custom tooltip ("title") that appears when the mouse moves over a cluster.

**Comment by Valachio** [comment]
@garylittleRLP 

What is a custom calculator?  Is that a feature built in MarkerClustererPlus or..?

I would like to show a label without having to hover over the markercluster.

I am already displaying information when the user hovers over the cluster. The idea is to provide price info without having to interact with the cluster at all. 

And thank you for the quick reply.
