### ISSUE TITLE
Cluster not repainted for new bounded zoom level after fitbounds

### ISSUE THREAD

**Issue by mikemania** [googlemaps/v3-utility-library#469]
I am calling fitbounds to center the map after marker creation. The issue is the clusters will be initially drawn as if the zoom level were before the fitbounds zooms in/out the map view. Zooming manually after will trigger cluster repaint and fix the issue. So if the map were zoom 3 initially, and the fitbounds zooms to 6, the clustering behaves as if it were still zoom 3.

**EDIT**: Actually, this issue happens even if I don't use fitbounds and use zoom().

	var locations;
	clearLocations();
	$.ajax({
		type:'GET',
		url:'url.php',
		dataType: "json",
		data:{
			region:region
		},
		success:function(data){
			
			markerNodes = data;
			//total results for counter total number
			totalResults = markerNodes.length;

			for (i = 0; i < markerNodes.length; i++) {  
				
				var id = markerNodes[i].id;
				var name = markerNodes[i].company;
				var distance = '';
				var latlng = new google.maps.LatLng(
					parseFloat(markerNodes[i].lat),
					parseFloat(markerNodes[i].lng)
				);

				//create marker and event listener attach function
				createMarker(id, latlng, name, distance, i);
				bounds.extend(latlng);
				
			}

			markerClusterer = new MarkerClusterer(map, markers, {imagePath: 'img/maps/m'});
			markerClusterer.setMaxZoom(minClusterZoom);

			if (bounds.getNorthEast().equals(bounds.getSouthWest())) {
				var extendPoint1 = new google.maps.LatLng(parseFloat(bounds.getNorthEast().lat() + 0.001), parseFloat(bounds.getNorthEast().lng() + 0.001));
				var extendPoint2 = new google.maps.LatLng(parseFloat(bounds.getNorthEast().lat() - 0.001), parseFloat(bounds.getNorthEast().lng() - 0.001));
				bounds.extend(extendPoint1);
				bounds.extend(extendPoint2);
			}
			
			map.fitBounds(bounds);
			//markerClusterer.repaint();

		}
	});

**Comment by CrocoDillon** [comment]
I have the same issue, this is my workaround for now:

```js
map.fitBounds(bounds)

setTimeout(() => {
  markerCluster.resetViewport()
  markerCluster.redraw()
})
```

**Comment by mikemania** [comment]
@CrocoDillon That didn't quite work for me, but using your snippet I did figure out something for my use case.
```javascript
google.maps.event.addListenerOnce(map, 'idle', function() {
	markerClusterer.resetViewport()
	markerClusterer.redraw()
});
```
Basically just calls the redraw on map idle. Would have been ideal if `fitBounds` had a callback.

**Comment by RobinDeHerdt** [comment]
Phew, glad I found this issue! Took me a while to figure out what was going wrong.
Here is the code I used, which is a combination of the code snippets provided by @CrocoDillon & @mikemania
```
google.maps.event.addListenerOnce(map, 'idle', function() {
  markerClusterer.repaint();
});
```
