### ISSUE TITLE
MarkerManager Unavailable as NPM Package

### ISSUE THREAD

**Issue by lucashby** [googlemaps/v3-utility-library#474]
As the title states, MarkerManager is unavailable as NPM package.  Would it be possible to get one published?

**Comment by jpoehnelt** [comment]
Now available here: https://www.npmjs.com/package/@googlemaps/markermanager

**Comment by outaTiME** [comment]
Great, but why different namespace from `markerclustererplus` or `markerwithlabel`? it should not be  `@google/markermanager`?

**Comment by jpoehnelt** [comment]
To avoid naming conflicts. All new packages from https://github.com/googlemaps org are going under @googlemaps.

**Comment by outaTiME** [comment]
yup, understood but why not the markerclustererplus and markerwithlabel?

**Comment by jpoehnelt** [comment]
>yup, understood but why not the markerclustererplus and markerwithlabel too?

perhaps after transition to typescript
