### ISSUE TITLE
arcgislink.js layerOnClick return geometry

### ISSUE THREAD

**Issue by azhaordi** [googlemaps/v3-utility-library#476]
Does arcgislink.js support MapOverlay OnClick to return a geometry reference? I needed it to perform a query on the added layer to retrieve the attributes of clicked area. 

http://sampleserver3.arcgisonline.com/ArcGIS/SDK/REST/geometry.html

**Comment by amuramoto** [comment]
Sorry, not familiar with arcgislink. Your best bet is to ask about this on StackOverflow

https://stackoverflow.com/questions/tagged/google-maps-api-3

**Comment by amuramoto** [comment]
reopening - misread the question

**Comment by amuramoto** [comment]
I think you show be able to call `fromOverlaystoJson()` on the overlay object in the onclick event
