### ISSUE TITLE
CORS error when contacting Google Maps 

### ISSUE THREAD

**Issue by akuma8** [googlemaps/v3-utility-library#478]
Hi,
Does someone know the reason of this error and how can I solve it?

<img width="948" alt="google api cors" src="https://user-images.githubusercontent.com/2613496/53629319-8c717d00-3c0d-11e9-9e84-a47c9ee285d6.PNG">

Thanks

**Comment by akuma8** [comment]
Is there someone here?

**Comment by amuramoto** [comment]
Hi! Please ask debugging questions on our StackOverflow tag:

https://stackoverflow.com/questions/tagged/google-maps-api-3
