### ISSUE TITLE
infobox never close when zooming out with cluster

### ISSUE THREAD

**Issue by Colir** [googlemaps/v3-utility-library#479]
Hello.
When we zoom on a marker , and open up an infobox,
if we zoom out, and return to a zoom level which display the maker in a cluster, the infobox never close.

This is problem not appening with a very older infobox lib (* @version 1.1.13 [March 19, 2014]).
With this old version, when we zoom out to a cluster size, the previously opened infobox dissapear, which is really great.

Thank you.

**Comment by amuramoto** [comment]
You can call `close()` on the infobox in an event listener for the `zoom_changed`. This lets you determine what's the best zoom level differential to trigger the close
