### ISSUE TITLE
markerclustererplus with Vue, imagePath targeting assets folder

### ISSUE THREAD

**Issue by rreckonerr** [googlemaps/v3-utility-library#480]
Hello! 
I'm using markerclustererplus in a Vue project and I can't figure out how to target local images in assets folder. I have created a question on [stackoverflow.](https://stackoverflow.com/questions/55040966/vue-how-to-point-to-assets-folder-from-js-method)

I'd appreciate any help.

**Comment by amuramoto** [comment]
Hi! StackOverflow is your best bet for how-to/debugging questions
