### ISSUE TITLE
how to change labelClass onClick external link

### ISSUE THREAD

**Issue by ohakubi** [googlemaps/v3-utility-library#482]
I having a issue about changing labelClass(I mean color of the marker) when external link clicked. I am trying to do it in `clickMark()`

```
updateMarkers: function() {
  //
  //
  this.marker = new MarkerWithLabel({
     icon: "/img/arrow.png",
     position: position,
     map: map,
     labelClass: "markerClass",
     labelAnchor: new google.maps.Point(50, 50),
     labelContent: label,
     url: "/pages/" + estates[i].id,
  });

  this.markers.push(this.marker);

  //
  //
  }
},
clickMark: function(id) {
     this.map.setCenter(this.markers[id].getPosition());
     this.markers[id].setOptions({labelClass:'markerClass2'});
     this.map.setZoom(12);
     google.maps.event.trigger(this.markers[id], 'mouseover');
},
```

I give new class with setOptions, it's working but not properly. it's changing color just for 1 second and then going back to old class... I am trying to change label class, until when I click a different link. Then it can go back to old class...

**Comment by amuramoto** [comment]
Please ask debugging questions on our StackOverflow tag

https://stackoverflow.com/questions/tagged/google-maps-api-3
