### ISSUE TITLE
MarkerClusterer is not defined

### ISSUE THREAD

**Issue by thehitechpanky** [googlemaps/v3-utility-library#483]
Uncaught (in promise) ReferenceError: MarkerClusterer is not defined.

I have already loaded the script markerclusterer.js and trying to use it. But it keeps on giving the error.

PS. I am using requirejs in my code too.

**Comment by amuramoto** [comment]
Please ask debugging questions on our StackOverflow tag

https://stackoverflow.com/questions/tagged/google-maps-api-3
