### ISSUE TITLE
Typescript defintions

### ISSUE THREAD

**Issue by jpike88** [googlemaps/v3-utility-library#490]
It's the year 2019, new projects are rarely pure JS. I'd like TS defintions please.

**Comment by bamnet** [comment]
The DefinitelyTyped project provides a pretty comprehensive set of TypeScript definitions for the Google Maps JavaScript API.

Check out [@types/googlemaps](https://www.npmjs.com/package/@types/googlemaps) and the [googlemaps](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/googlemaps) folder of the DefinitelyTyped/DefinitelyTyped repo.

**Comment by jpike88** [comment]
They're out of date though...

**Comment by ruslankaminsky** [comment]
I don't see there MarkerClusterer, am I missing something?

**Comment by terencehonles** [comment]
@ruslankaminsky `@types/markerclustererplus`

**Comment by jpoehnelt** [comment]
see #571 and #572
