### ISSUE TITLE
Broken path to cluster images

### ISSUE THREAD

**Issue by wowxoxo** [googlemaps/v3-utility-library#514]
Hi guys. I use vue2-google-maps package, that works with this library.

After commit  24c33310f1c566f247d0ab38120a88afffeea250 reorganize with lerna (#512) path to cluster images m1, m2, m3, m4, m5 has been broken. I think it happend cause folder structure has been changed.

For example, the link to the m1 icon give me 404 in Chrome console:
https://raw.githubusercontent.com/googlemaps/v3-utility-library/master/markerclustererplus/images/m1.png

**Comment by johnBgood** [comment]
Same issue with MarkerClusterer from react google maps

**Comment by desmoteo** [comment]
Same here

**Comment by germanow** [comment]
New URL: https://raw.githubusercontent.com/googlemaps/v3-utility-library/master/packages/markerclustererplus/markerclustererplus/images/m1.png

Quick fix for Vue:
```js
GmapCluster.props.styles.default = function() {
  return [
    {
        textColor: 'balck',
        url: 'https://raw.githubusercontent.com/googlemaps/v3-utility-library/master/packages/markerclustererplus/markerclustererplus/images/m1.png',
        height: 52,
        width: 53
    },
    {
        textColor: 'balck',
        url: 'https://raw.githubusercontent.com/googlemaps/v3-utility-library/master/packages/markerclustererplus/markerclustererplus/images/m2.png',
        height: 55,
        width: 56
    },
    {
        textColor: 'balck',
        url: 'https://raw.githubusercontent.com/googlemaps/v3-utility-library/master/packages/markerclustererplus/markerclustererplus/images/m3.png',
        height: 65,
        width: 66
    },
    {
        textColor: 'balck',
        url: 'https://raw.githubusercontent.com/googlemaps/v3-utility-library/master/packages/markerclustererplus/markerclustererplus/images/m4.png',
        height: 77,
        width: 78
    },
    {
        textColor: 'balck',
        url: 'https://raw.githubusercontent.com/googlemaps/v3-utility-library/master/packages/markerclustererplus/markerclustererplus/images/m5.png',
        height: 89,
        width: 90
    }
  ]
}
Vue.use(GmapCluster)
```
Afterwards, you can download the images and set url to this images in your web server.

**Comment by desmoteo** [comment]
As a temporary workaround on react google maps, you can change the package.json dependency to
"react-google-maps": "desmoteo/react-google-maps#fix-markerclusterpath",

**Comment by jpoehnelt** [comment]
**Please don't depend on this file from master.** Use a link to a specific commit or host it elsewhere. https://github.com/googlemaps/v3-utility-library/raw/bd55f49fc8492207d30e179d280c00aa8b5016e0/markerclusterer/images/m2.png
