### ISSUE TITLE
Module not found: Can't resolve '@google/markerclustererplus

### ISSUE THREAD

**Issue by osimuka** [googlemaps/v3-utility-library#524]
Thanks for stopping by to let us know something could be better!

---
**PLEASE READ** 

If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/). This will ensure a timely response. 

Discover additional support services for the Google Maps Platform, including developer communities, technical guidance, and expert support at the Google Maps Platform [support resources page](https://developers.google.com/maps/support/). 

If your bug or feature request is not related to this particular library, please visit the Google Maps Platform [issue trackers](https://developers.google.com/maps/support/#issue_tracker).

Check for answers on StackOverflow with the [google-maps](http://stackoverflow.com/questions/tagged/google-maps) tag.

---

Please be sure to include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title (for example, "Places: ...")
2. OS type and version
3. Library version and other environment information

#### Steps to reproduce

  1. MarkerClusterPlus not importing from node modules, `version 2.1.11`

#### Code example

```react js
var MarkerClusterer = require("@google/markerclustererplus");
```

#### Stack trace
```
./<location.js>
web             | Module not found: Can't resolve '@google/markerclustererplus' in '<location>'
```

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by jpoehnelt** [comment]
I recently modified the configuration for this markerclusterplus in version `3.0.0-alpha.0` using rollup and es modules. Please give it a try: https://www.npmjs.com/package/@google/markerclustererplus/v/3.0.0-alpha.0.

**Comment by osimuka** [comment]
> I recently modified the configuration for markerclusterplus in version `3.0.0-alpha.0` using rollup and es modules. Please give it a try: https://www.npmjs.com/package/@google/markerclustererplus/v/3.0.0-alpha.0.

Still getting thesame error message
node-packages.json
```
...
"@google/markerclustererplus": "^3.0.0-alpha.0",
...
```

**Comment by jpoehnelt** [comment]
I'm unable to reproduce with webpack for 2.1.11. See https://github.com/jpoehnelt/v3_utility_library_bug_524.

There is a typo in the 3.0.0-alpha that needs to be fixed due to mismatch in [package.json](https://github.com/googlemaps/v3-utility-library/blob/master/packages/markerclustererplus/package.json#L25-L27) and rollup.config.js.

**Comment by osimuka** [comment]
> I'm unable to reproduce with webpack for 2.1.11. See https://github.com/jpoehnelt/v3_utility_library_bug_524.
> 
> There is a typo in the 3.0.0-alpha that needs to be fixed due to mismatch in [package.json](https://github.com/googlemaps/v3-utility-library/blob/master/packages/markerclustererplus/package.json#L25-L27) and rollup.config.js.

Thanks for the speedy reply, found out the root cause of the issue. It was the docker container we are using that was cause the issue.
