### ISSUE TITLE
Conditional export as module for markerclustererplus

### ISSUE THREAD

**Issue by outaTiME** [googlemaps/v3-utility-library#530]
Hi, it could be possible to preserve conditional module export for markerclustererplus like the old version (previous to lerna) like this?

https://github.com/googlemaps/v3-utility-library/blob/bd55f49fc8492207d30e179d280c00aa8b5016e0/markerclustererplus/src/markerclusterer.js#L1659

Thanks !!!

**Comment by jpoehnelt** [comment]
The `dist/markerclusterplus.umd.js` does this already: ` typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() : ...`. What is the specific use case or issue you are trying to solve?

**Comment by outaTiME** [comment]
Hi @jpoehnelt, 
for a long time im using this library as bower component and i didnt found the dist folder, it could be included bundle ?

**Comment by jpoehnelt** [comment]
Try `markerclustererplus@3.0.0-beta.1`. https://unpkg.com/browse/@google/markerclustererplus@3.0.0-beta.1/dist/

**Comment by outaTiME** [comment]
im using few more packages like markermanager, markerwithlabel and markerclusterplus at this moment (imho) the more safest way to preserve this dependencies is using the last commit without lerna:

https://github.com/googlemaps/v3-utility-library/tree/bd55f49fc8492207d30e179d280c00aa8b5016e0

I prefer to wait until all packages are available individually.

**Comment by outaTiME** [comment]
BTW, markermanger is not already published to NPM, right ?

**Comment by jpoehnelt** [comment]
The only published packages are markerclusterer, markerclustererplus, and markerwithlabel. If you open issues for the ones you use, I can begin the process and prioritize those.

**Comment by outaTiME** [comment]
Great @jpoehnelt, you could publish the markermanager to npm too? it would be very handy, thanks !!!

**Comment by jpoehnelt** [comment]
markermanager updated in #542, have not published yet

**Comment by jpoehnelt** [comment]
closing in favor of #474
