### ISSUE TITLE
marker clusterer lib must be included before maps js api

### ISSUE THREAD

**Issue by amuramoto** [googlemaps/v3-utility-library#563]
It appears from the JSFiddle example in our docs (https://developers.google.com/maps/documentation/javascript/adding-a-google-map) that the map load will fail if the script tag for the marker clusterer lib is included after the script tag for the maps JS API.

Let's investigate ASAP if there's a way to mitigate this or if the docs need to be updated to reflect this requirement. @jpoehnelt I think we should treat this as a P0.

**Comment by jpoehnelt** [comment]
There isn't anything to be done except change the order. Solutions are entirely dependent on frameworks and patterns used.  One solution is https://github.com/googlemaps/v3-utility-library/tree/master/packages/loader.
