### ISSUE TITLE
Adding a way so that the InfoWindow can get a path to an html file

### ISSUE THREAD

**Issue by ThomasBiede** [googlemaps/v3-utility-library#566]
Today I wanted to style and make an InfoWindow for my marker, but it was pretty weird/difficult to design. I think that having to input and loooong html string as content is not very elegant. It would be better if I could set as the content string a path to a html file, instead of the html string.

it should look something like this:
const marker = new google.maps.InfoWindow({ content: './path/to/html/file' });

This would be a much more elegant approach and would imporve the developing experience because i wouldn't have to switch between an editing html file and copying the html document into the content string

**Comment by jpoehnelt** [comment]
The problem with this is that the library needs to be opinionated about the mechanism for loading that file and it will blow up with dependencies for doing so. 

How are you loading the html file currently?

**Comment by ThomasBiede** [comment]
Currently I am using a filereader to read in the html file as a string but it is not very sophisticated because it can't read the referenced css file and reference it to the html-nodes
