### ISSUE TITLE
Speed of zoom

### ISSUE THREAD

**Issue by PietroLaGrotta** [googlemaps/v3-utility-library#576]
Is it possible to set the speed of zoom?
Now, when I click on cluster, map zooms the view, but level of zoom changes too speedly.
I need to set, if is possible, the new level of zoom, on click on cluster. 
Thanks in advance :-)

**Comment by jpoehnelt** [comment]
This isn't supported by the underlying Google Maps JavaScript library([reference](https://developers.google.com/maps/documentation/javascript/reference/)).  You can request this feature here: [https://issuetracker.google.com/savedsearches/558438](https://issuetracker.google.com/savedsearches/558438).
