### ISSUE TITLE
paint cluster  in one location without making markers

### ISSUE THREAD

**Issue by Jigunho** [googlemaps/v3-utility-library#578]
![image](https://user-images.githubusercontent.com/17794793/69115894-ab7eaa80-0acd-11ea-9574-b172dad10365.png)

hello, I am developing web site using google map,

I want to show  cluster like following image, 

In one location,  having over 1000 markers markers and represent cluster by marker's count.

I edited prototype.calculator_ function , but I think there is no solution like this situation.

Is there any soltion ?

**Comment by garylittleRLP** [comment]
Yes, of course you can do it with MarkerClusterer Plus, this is exactly what it is designed to do. Of course, it may act a little slowly if you are trying to cluster thousands of markers.

**Comment by jpoehnelt** [comment]
Closing this unless there are specific issues encountered.
