### ISSUE TITLE
Changelog and docs on markerclustererplus?

### ISSUE THREAD

**Issue by janosh** [googlemaps/v3-utility-library#579]
Breaking changes [were published in markerclustererplus v3](https://www.npmjs.com/package/@google/markerclustererplus/v/3.0.0) a month ago but it's hard to figure out what they were as the [changelog seems out of date](https://github.com/googlemaps/v3-utility-library/blob/master/packages/markerclustererplus/CHANGELOG.md).

Also [the docs](https://googlemaps.github.io/v3-utility-library/index.html) seem to contain no more than a single sentence on markerclustererplus:

> @google/markerclustererplus - Extended version of @google/markerclusterer

Am I missing something?

**Comment by jpoehnelt** [comment]
Any recent breaking changes should have accompanied a major version, sorry if that was not the case.

The prior **docs** were out of date and did not accomodate typescript well. There is an effort to move more packages to typescript #572, #571, #573. 

The **changelog** will soon be automated using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

**Comment by janosh** [comment]
> Any recent breaking changes should have accompanied a major version, sorry if that was not the case.

I wasn't quite clear. It _was_ a major version (from 2.x to 3.x) but `changelog.md` has no info on v3 changes.

> The changelog will soon be automated using conventional commits.

Cool, looking forward to that.

> The prior docs were out of date and did not accomodate typescript well. There is an effort to move more packages to typescript #572, #571, #573.†

I noticed that. `markerclusterer.d.ts` was actually the most useful documentation I could find for this package. 😄

**Comment by jpoehnelt** [comment]
Hopefully all of this will be improving over the coming months! It's just going to take a little while to get there and it might be a little messy. The major version change wasn't so much breaking the interface but the change in packaging and modules.

>I noticed that. markerclusterer.d.ts was actually the most useful documentation I could find for this package.

Should be getting better soon with typedoc once #590 is completed and merged!

**Comment by jpoehnelt** [comment]
closing this with #590

**Comment by jpoehnelt** [comment]
https://googlemaps.github.io/v3-utility-library/modules/_google_markerclustererplus.html

**Comment by janosh** [comment]
Cool, much better now! 👍
