### ISSUE TITLE
Add es5-version to markerclustererplus npm package

### ISSUE THREAD

**Issue by dummdidumm** [googlemaps/v3-utility-library#585]
Since markerclustererplus [was converted to use the new class-syntax](https://github.com/googlemaps/v3-utility-library/commit/32042f81ee37a7834b16f9e99bcf208416be2fe9), it is not usable as an npm-package anymore when using Typescript and targeting es5. Reason: Typescript does not transpile javascript files, so it ends up with the class-syntax in the compiled output. It would be great if you could add a es5-version to the npm-package.

This maybe also applies to other packages (haven't looked into it because I only need markerclustererplus).

**Comment by jpoehnelt** [comment]
published to https://github.com/googlemaps/v3-utility-library/releases/tag/%40google%2Fmarkerclustererplus%403.0.6
