### ISSUE TITLE
Custom css class for ClusterIcon defined by ClusterIconStyle

### ISSUE THREAD

**Issue by thekip** [googlemaps/v3-utility-library#589]
Seems this library was created quite a time ago when CSS was not so strong as now and hasn't allowed doing all these things like nowadays. 

Today in some cases it has absolutely no sense to use image or SVG because you can express style of marker only using css, our example:

![image](https://user-images.githubusercontent.com/1586852/70694928-ee90ff80-1cc0-11ea-85ad-c5e7465eb721.png)

This can be created using one div element and two pseudos (`:before`, `:after`). No icon file needed, no problems with retina screens.

Btw now it also not possible to define a different style for hover of the icon, for example, make it bigger, or change the opacity.

So my proposal consists of two parts: 
1. Add `className` property to `ClusterIconStyle` interface and use it on the root Cluster div element. 
2. [optional, BREAKING_CHANGE] Move defining default styles definition such as `textColor` `textSize` `fontWeight` and etc from `ClusterIcon.useStyle` to `MarkerClusterer.setupStyles_` to be able to completely override all styles by supplying custom ClusterIconStyle.
Since we are going to style cluster icons with css rules, hardcoded inlined styles will be impossible to override from a stylesheet.

And from my point of view, this will be a good direction to move, because styling with native css rules is better and flexible than using pre-defined "css like, but not exactly" properties presented now.

The next step may be is allowing to pass a function which will be used to generate a cluster icon element. Which accept `HTMLDivElement` and cluster properties as input and returns a new (or augmented) element, for those cases where default layout isn't enough.

Or maybe I wrong and this is by design and created for performance or other not obvious reason? 

BTW I can prepare a PR with these changes.

**Comment by jpoehnelt** [comment]
I think these would be great changes and support both 1 and 2. Seems like `HTMLDivELement` could be a separate change?

**Comment by thekip** [comment]
Yep, passing a function to create a cluster will be a separate change. 

BTW, I would like to finish and merge this https://github.com/googlemaps/v3-utility-library/pull/590  before starting working on changes mentioned in this issue.
