### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by jtgn** [googlemaps/v3-utility-library#593]
The example on packages/markerclustererplus/examples/advanced_example.html don't work anymore. I always get the error "uncaught ReferenceError: MarkerClusterer is not defined". 

Has the example not been updated along with the code? Is this planned in the near future?

**Comment by thekip** [comment]
How did you run them? I 've just tested and it works. 

I used this commands:
```
npm i
cd ./packages/markerclustererplus
npm run prepare
npx http-server ./docs
```

**Comment by jpoehnelt** [comment]
@jtgn let me know if you are still having issues. The examples are now rendered on master and can be found linked in https://googlemaps.github.io/v3-utility-library/modules/_google_markerclustererplus.html or in the readme of the package.

**Comment by jtgn** [comment]
Thanks to both of you @jpoehnelt and @thekip.  Both hints helped a lot!
