### ISSUE TITLE
[markerclustererplus] Expose examples

### ISSUE THREAD

**Issue by thekip** [googlemaps/v3-utility-library#595]
Now examples are only accessible thru the code. You need to clone, prepare and then run HTTP server to explore examples. 
I'd like to expose these examples to users. I checked the commands in package.json and could not find how docs are deployed to github. 
Could you set up deployment to also deploy `packages/markerclustererplus/examples` folder together with `./docs` and add a link from  markerclustererplus docs page.

**Comment by jpoehnelt** [comment]
closed by #598 and #596
