### ISSUE TITLE
MarkerClustererPlus published npm package is entire source, not the build dist

### ISSUE THREAD

**Issue by doom777** [googlemaps/v3-utility-library#600]
The package that is deployed to npm, is just a zip of the entire source of the library, instead of the distributable.

To fix, run rollup, then cd into dist, and run npm publish from the `dist` directory

**Comment by jpoehnelt** [comment]
I don't see this, https://unpkg.com/browse/@google/markerclustererplus@4.0.1/dist/. Please reopen with more information.

**Comment by jpoehnelt** [comment]
Actually you are right. Misinterpreted.

**Comment by doom777** [comment]
Why not just publish dist with images and package.json inside?
