### ISSUE TITLE
Uncaught SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by smuellerus** [googlemaps/v3-utility-library#601]
I am including the current version using:

`<script src="js/markerclusterer.js"></script>
`

and the following error is shown:

`Uncaught SyntaxError: Unexpected token 'export'`

Line 1271

Any ideas?

**Comment by jpoehnelt** [comment]
Yes, the markerclusterer.js needs to be transpiled. For local development, I would use those outputs in the dist folder instead. You may also use the unpkg link here: https://unpkg.com/@google/markerclusterer@2.0.6/dist/markerclusterer.min.js.  You can browse outputs here: https://unpkg.com/browse/@google/markerclusterer@2.0.6/dist/

**Comment by smuellerus** [comment]
I am now using markerclustererplus which worked out of the box.
