### ISSUE TITLE
Loaded event from MarkerManager not fired

### ISSUE THREAD

**Issue by outaTiME** [googlemaps/v3-utility-library#602]
Hi guys,  
I upgrade to new MarkerManager from NPM module (v.0.0.4) and 'loaded' event doesn't fired anymore something missing in docs?

Thanks !!!

**Comment by jpoehnelt** [comment]
This was not removed and is likely a regression.

**Comment by jpoehnelt** [comment]
Looks like all the events may not be firing.

**Comment by jpoehnelt** [comment]
I'm unable to recreate here: https://jsfiddle.net/jwpoehnelt/d6cukq2b/. Looking at the code more closely, there is likely a race condition happening. Feel free to fork the jsfiddle to get a reproducible example. I'm going to close this for now as I believe the race condition has always been there.
