### ISSUE TITLE
package.json module definition

### ISSUE THREAD

**Issue by paxapy** [googlemaps/v3-utility-library#608]
hi, not sure if it's actually a bug, but i have no other ideas how to handle it.

#### Environment details
i'm trying to use `@google/markerclustererplus` with angular project and import clusterer like this
```
import MarkerClusterer from '@google/markerclustererplus';
```
in my service.

#### An Issue
what i've noticed is that in my vendor.js i got whole contents of `dist/markerclustererplus.esm.js` and so it's not going to work with anything that doesn't support ES2015.

I also checked that in `package.json` you have 
```
"main": "dist/markerclustererplus.umd.js",
"module": "dist/markerclustererplus.esm.js",
```
which means i always will get `esm` version to be bundled. 
and as i can see from [rollup.config](https://github.com/googlemaps/v3-utility-library/blob/master/packages/markerclustererplus/rollup.config.js) you not going to transpile code for this.
is there way i can manage what file will be bundled in vendor.js? if i can get umd it will solve my problem.

**Comment by jpoehnelt** [comment]
>is there way i can manage what file will be bundled in vendor.js?

it depends entirely on the build tool you are using. in this case you need to transpile the code. you can read more here: https://stackoverflow.com/questions/42708484/what-is-the-module-package-json-field-for
