### ISSUE TITLE
open_now deprecation thrown from PlacesService.getDetails, but I don't even asked for it (and my request is well formed)

### ISSUE THREAD

**Issue by RomainMazB** [googlemaps/v3-utility-library#614]
Hi, I need to find places for a specific types (hair_care in example) around a LatLng object, filter them for a specific postal code, and then fetch the detailled places returned.

nearbySearch works well, then to filter the 20 places returned for a specific postal code, I'm using the getDetails method with the address_component field.

The problem is: for 20 places, the console catches 1600 open_now deprecation error. What is weird (in addition of the huge number of errors), is the fact that I didn't even asked for the open_now fields.

I'm working in VueJS with the [load-google-maps-api](https://github.com/yuanqing/load-google-maps-api) lib.
#### Code example
```javascript
const basic_search_fields = [
    'place_id',
    'name',
    'address_components'
]
/**
    * Construct a place search request
    */
createPlaceRequestFor: function (place) {
    // Init the request with the fixed datas
    let request = {
        placeId: place.place_id,
        fields: basic_search_fields
    }
    return request
},
executePlaceRequest: function (request) {
    return new Promise((resolve, reject) => {
        console.log(request)
        this.PlacesService.getDetails(request, (results, status) => {
            if (status == this.Google.places.PlacesServiceStatus.OK) {
                console.log(results)
                resolve(results)
            }
            reject(status)
        })
    })
}
```
A screenshot of my requests / results from the console.log present is the previous code:
![console log](https://user-images.githubusercontent.com/53976837/74238598-6a65f300-4cd6-11ea-97ba-ab0775b155cb.png)

If I make another request without reloading the page, thousands and thousands error appears in console until it crash my browser...
#### Stack trace
1600 open_now deprecation for 20 places!

#### Environment details

1. Places
2. Ubuntu 18.04
3. v3.39.10

**Comment by jpoehnelt** [comment]
I'm unable to recreate https://jsfiddle.net/jbnk5o74/ (needs API key to function). Can you get a minimal example of this?

**Comment by RomainMazB** [comment]
I also can't reproduce the errors in jsfiddle. What I'm trying to do is [something like that](https://jsfiddle.net/r6d7qcsg/), which works in fiddle...

The fact is, in my whole project I don't even mention the open_now or utc_offset fields:
![Search screenshot](https://user-images.githubusercontent.com/53976837/74354394-95764280-4dbb-11ea-92ca-8d1eec1932fa.png)

I can't figure why this happens...

![errors screenshot](https://user-images.githubusercontent.com/53976837/74354687-04ec3200-4dbc-11ea-874d-a66a3740ac83.png)

**Comment by jpoehnelt** [comment]
I suggest filing a bug report here: [Maps JavaScript Issue Tracker](https://issuetracker.google.com/issues/new?component=188853&template=788207), but it is difficult to debug without a reproducible case that can be shared.
