### ISSUE TITLE
markerclustererplus - IE not supported

### ISSUE THREAD

**Issue by jcmillett** [googlemaps/v3-utility-library#630]
The latest version of markerclustererplus v5.0.1 doesn't seem to work in IE due to the use of Object.assign. Shouldn't the minified file be including that as a polyfill?

Replication steps:
1.) In Internet Explorer 11, navigate to the simple example from the documentation: https://googlemaps.github.io/v3-utility-library/packages/markerclustererplus/examples/simple_example.html
2.) Notice that the cluster images don't appear
3.) Open IE's devtools
4.) Reload the page
5.) Notice error in the devtools console: Object doesn't support property or method 'assign'

**Comment by garylittleRLP** [comment]
Yes, it appears that MSIE 11 does not support Object.assign.

The polyfill at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign should be applied.

**Comment by jpoehnelt** [comment]
should be available in https://www.npmjs.com/package/@google/markerclustererplus/v/5.0.2

**Comment by jcmillett** [comment]
@jpoehnelt I just tested with v5.0.2 and I'm still seeing the same issue. Does the @babel/env preset need to be configured so that useBuiltIns is set to usage?

**Comment by jpoehnelt** [comment]
Odd, when I built locally it did not use Object.assign in the dist. Let me check again.

**Comment by jpoehnelt** [comment]
Try https://www.npmjs.com/package/@google/markerclustererplus/v/5.0.3 😄
