### ISSUE TITLE
Use MarkerClusterPlus in react web

### ISSUE THREAD

**Issue by Bing619** [googlemaps/v3-utility-library#642]
How to use MarkerClusterPlus with GoogleMap in an react web?
import MarkerClusterer from '@google/markerclustererplus'
Thanks

**Comment by jpoehnelt** [comment]
Do you have some code you can share to be help you troubleshoot? You may get a better response on [StackOverflow](https://stackoverflow.com/).

**Comment by Bing619** [comment]
I use this is ok:
const { MarkerClusterer } = require("react-google-maps/lib/components/addons/MarkerClusterer");
<img width="668" alt="屏幕快照 2020-03-31 上午10 53 46" src="https://user-images.githubusercontent.com/53731175/77982513-1b842380-733f-11ea-8910-48012ada9621.png">

But when i use this is error:import MarkerClusterer from '@google/markerclustererplus';
<img width="698" alt="屏幕快照 2020-03-31 上午11 00 56" src="https://user-images.githubusercontent.com/53731175/77982546-2f2f8a00-733f-11ea-8df1-c83783da580b.png">
![屏幕快照 2020-03-31 上午11 03 12](https://user-images.githubusercontent.com/53731175/77982560-3c4c7900-733f-11ea-9569-867921363dc6.png)

So i don't know how to use by react. which use html is ok.

Thank you very mush!

**Comment by jpoehnelt** [comment]
The `read propery 'firstChild'` is a failure to add the map to a specific dom node. I'm not well versed in react. You might get better support on Stackoverflow or react-google-maps for this issue.

**Comment by Bing619** [comment]
Thanks, i've asked this question on react-google-maps.
