### ISSUE TITLE
Marker cluster stuck on map in google maps JS API (version 3.39)

### ISSUE THREAD

**Issue by poojarai** [googlemaps/v3-utility-library#645]
Thanks for stopping by to let us know something could be better!

---
**PLEASE READ** 

If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/). This will ensure a timely response. 

Discover additional support services for the Google Maps Platform, including developer communities, technical guidance, and expert support at the Google Maps Platform [support resources page](https://developers.google.com/maps/support/). 

If your bug or feature request is not related to this particular library, please visit the Google Maps Platform [issue trackers](https://developers.google.com/maps/support/#issue_tracker).

Check for answers on StackOverflow with the [google-maps](http://stackoverflow.com/questions/tagged/google-maps) tag.

---

Please be sure to include as much information as possible:

#### Environment details

1. Using Firefox version- 68.4.1
2. Google Maps JS API version- 3.39
3. Marker Clusterer API version- 2.1.2

#### Steps to reproduce

  In our project we are using Google Maps JS API with MarkerClusterer Plus library.
When we click on any shape on google maps, focus shifted to the selected shape, at that time map should shift with updated marker clusters but previously created marker cluster images stuck on map till next action (like drag, click, tab switch).
We have observed this issue in Firefox version 68.4.1.
Its working fine in Google Chrome browser with latest version

![sample](https://user-images.githubusercontent.com/18527583/79736290-33840d00-8317-11ea-94ef-b7877cab5c82.PNG)
.

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by jpoehnelt** [comment]
Could you set up a simple jsfiddle or similar?
