### ISSUE TITLE
How to install from npm?

### ISSUE THREAD

**Issue by strarsis** [googlemaps/v3-utility-library#648]
I want to use the MarkerLabel package, how can I install it using npm?

**Comment by tkreyche** [comment]
I had the same question and finally figured out how to use it from the unpkg.com content delivery network, after spending hours reading the documentation (not helpful) and looking over various examples online. This appears to grab the latest version although you can also specify a particular version. It's unclear to me why this is neither documented nor obvious.

Just add this reference or you can also just download it from the same link. 

<script src="https://unpkg.com/%40google/markerclustererplus/dist/markerclustererplus.min.js"></script>

**Comment by strarsis** [comment]
@tkreyche: Ah, this explains how to use the script at all.
But I also want to build it into the app when using webpack, for this I have to somehow include the whole library with all of its files.

**Comment by jpoehnelt** [comment]
Marker with label is available from npm. https://github.com/googlemaps/v3-utility-library/tree/master/packages/markerwithlabel#npm
