### ISSUE TITLE
Missing Map Ids functionality

### ISSUE THREAD

**Issue by dborstelmann** [googlemaps/v3-utility-library#660]
https://developers.google.com/maps/documentation/javascript/cloud-based-map-styling#add_map_ids_to_your_bootstrap_request_and_callback_function

I think this library is not updated to take mapIds as a parameter to loader unless I am missing something

**Comment by jpoehnelt** [comment]
See https://github.com/googlemaps/js-api-loader which is installable via `npm i @googlemaps/js-api-loader`.

**Comment by dborstelmann** [comment]
Thanks!
