### ISSUE TITLE
@googlemaps/loader: this.callback is not a function

### ISSUE THREAD

**Issue by asbjornh** [googlemaps/v3-utility-library#665]
Our error tracker has been picking up instances of the following error:

![image](https://user-images.githubusercontent.com/13281350/88540899-22345600-d014-11ea-8f09-aa55d6bd0a45.png)

On MacOS and iOS specifically the issue looks a little bit different:

![image](https://user-images.githubusercontent.com/13281350/88543687-9e309d00-d018-11ea-87aa-3e61aeaad4ba.png)

It's not very common (250 occurences in probably some thousand page loads), and I've been unable to reproduce it. I'm not sure what the impact is on users.

We're using `@googlemaps/loader@0.0.10`

<details>
<summary>Browsers in which the issue has occurred</summary>

Samsung Internet 12.0
Firefox Mobile 68.0
Chrome Mobile 80.0.3987
Chrome Mobile 84.0.4147
Edge Mobile 45.04.4
Chrome 79.0.3945
Chrome 81.0.4044
Chrome Mobile 83.0.4103
Chrome 80.0.3987
Chrome 83.0.4103
Samsung Internet 11.2
Chrome Mobile 81.0.4044
Chrome Mobile iOS 84.0.4147
Safari 13.1.1
Mobile Safari 14.0
Mobile Safari 13.0.3
Mobile Safari 12.1
Chrome Mobile iOS 83.0.4103
Mobile Safari 12.0
Mobile Safari 13.1.1
Mobile Safari 12.1.1
Mobile Safari 13.0.4
Mobile Safari 13.0.1
Mobile Safari 12.1.2
Mobile Safari 13.0.5
Mobile Safari 13.1
</details>

<details>
<summary>OSes in which the issue has occurred</summary>

Android 9
Windows 8.1
Windows 10
Android 8.0.0
Android 10
iOS 13.4
Mac OS X 10.15.5
iOS 14.0
iOS 13.2
iOS 13.2.3
iOS 12.2,2
iOS 13.5.1
iOS 12.4.1
iOS 12.4.7
iOS 12.1.2
iOS 13.5
iOS 12.3.1
iOS 12.4.6
iOS 13.3,11
iOS 13.1.3
iOS 12.4.5
iOS 13.3.1
iOS 13.4.1
</summary>

**Comment by jpoehnelt** [comment]
Can you try using [@googlemaps/js-api-loader](https://github.com/googlemaps/js-api-loader) instead?

**Comment by asbjornh** [comment]
Definitely! I completely missed the fact that `@googlemaps/loader` is deprecated. My bad! I guess I can just close this?
