### ISSUE TITLE
MarkerClusterPlus - fitMapToMarkers - add argument for bounds padding

### ISSUE THREAD

**Issue by alex-nextraq** [googlemaps/v3-utility-library#666]
We have currently implemented a method extremely similar to `fitMapToMarkers` with the primary difference, we need to have an offset using the padding parameter for the `fitBounds` method.

It would be marvelous if `fitMapToMarkers` could accept a `padding` parameter that it passes along to `fitBounds`.

While we have implemented our own version of `fitMapToMarkers` (we were not originally using MarkerClusterPlus) I would prefer to be able to fully leverage this library and not have duplicate code hanging around.

**Comment by jpoehnelt** [comment]
should be available in `@5.1.0`

**Comment by alex-nextraq** [comment]
Thank you!!
